=== zezzz555/Tp--ID/Tp-CidadesDoMundo/cidades.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- New XSD document created with EditiX XML Editor (http://www.editix.com) at Thu Jun 02 20:13:20 BST 2022 -->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:attribute name="uni" type="xsd:string"/>
	
<xsd:element name="nome" type="xsd:string"/>
	<xsd:element name="pais" type="xsd:string"/>
	<xsd:element name="bandeirapais" type="xsd:string"/>
	<xsd:element name="bandeiracidade" type="xsd:string"/>
	<xsd:element name="capital" type="xsd:string"/>
	<xsd:element name="presidente" type="xsd:string"/>
	<xsd:element name="clima" type="xsd:string"/>
	<xsd:element name="fuso" type="xsd:string"/>
	<xsd:element name="website" type="xsd:string"/>
	<xsd:element name="area">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:double">
					<xsd:attribute ref="uni" use="required"/>
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="densidade">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:double">
					<xsd:attribute ref="uni" use="required"/>
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="lingua" type="xsd:string"/>
	<xsd:element name="monumento" type="xsd:string"/>
	<xsd:element name="cidadegeminada" type="xsd:string"/>
	<xsd:element name="latitude" type="xsd:double"/>
	<xsd:element name="longitude" type="xsd:double"/>
	<xsd:element name="altitude" type="xsd:integer"/>
	<xsd:element name="nhabitantes" type="xsd:integer"/>
	<xsd:element name="codigopostal" type="xsd:integer"/>
	<xsd:element name="linguagens">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="lingua" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="monumentos">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="monumento" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="cidadesgeminadas">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="cidadegeminada" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="cidade">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="nome" minOccurs="1" maxOccurs="1"/>
				<xsd:element ref="pais" minOccurs="1" maxOccurs="1"/>
				<xsd:element ref="bandeirapais" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="bandeiracidade" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="capital" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="presidente" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="clima" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="fuso" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="website" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="area" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="densidade" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="linguagens" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="monumentos" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="cidadesgeminadas" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="latitude" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="longitude" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="altitude" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="nhabitantes" minOccurs="0" maxOccurs="1"/>
				<xsd:element ref="codigopostal" minOccurs="0" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<xsd:element name="catalogo">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="cidade" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== zezzz555/Tp--ID/Tp-CidadesDoMundo/cidades.xml
<?xml version="1.0" encoding="utf-8"?>
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cidades.xsd">
     <cidade>
          <nome>Madrid</nome>
          <pais>Espanha</pais>
          <bandeirapais>https://dwpt1kkww6vki.cloudfront.net/img/drapeau/120/194.png</bandeirapais>
          <bandeiracidade>https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Bandera_de_la_ciudad_de_Madrid.svg/100px-Bandera_de_la_ciudad_de_Madrid.svg.png</bandeiracidade>
          <capital>true</capital>
          <presidente>José Luis Martínez-Almeida Navasqües</presidente>
          <clima>Clima mediterrânico (Classificação climática de Köppen-Geiger: Csa)</clima>
          <fuso>UTC +1:00 (Europe/Madrid)</fuso>
          <website>https://www.madrid.es</website>
          <area uni="km2">605.77</area>
          <densidade uni="hab_km2">5391.7</densidade>
          <linguagens>
               <lingua>Espanhol</lingua>
          </linguagens>
          <monumentos>
               <monumento>//upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Panorama_de_Madrid_desde_el_parque_de_San_Isidro.JPG/296px-Panorama_de_Madrid_desde_el_parque_de_San_Isidro.JPG</monumento>
               <monumento>//upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Puerta_de_Alcal%C3%A1%2C_Madrid%2C_Espa%C3%B1a%2C_2017-05-18%2C_DD_14.jpg/148px-Puerta_de_Alcal%C3%A1%2C_Madrid%2C_Espa%C3%B1a%2C_2017-05-18%2C_DD_14.jpg</monumento>
               <monumento>//upload.wikimedia.org/wikipedia/commons/thumb/4/44/Plaza_Mayor_de_Madrid_06.jpg/144px-Plaza_Mayor_de_Madrid_06.jpg</monumento>
               <monumento>//upload.wikimedia.org/wikipedia/commons/thumb/d/da/MADRID_060518_MXALX_087.jpg/146px-MADRID_060518_MXALX_087.jpg</monumento>
               <monumento>//upload.wikimedia.org/wikipedia/commons/thumb/5/58/Palacio_de_Comunicaciones_-_46.jpg/146px-Palacio_de_Comunicaciones_-_46.jpg</monumento>
               <monumento>//upload.wikimedia.org/wikipedia/commons/thumb/1/1c/CTBA_%28Madrid%29_39.jpg/199px-CTBA_%28Madrid%29_39.jpg</monumento>
          </monumentos>
          <cidadesgeminadas>
               <cidadegeminada>Tirana</cidadegeminada>
               <cidadegeminada>Buenos Aires</cidadegeminada>
               <cidadegeminada>Bruxelas</cidadegeminada>
               <cidadegeminada>La Paz</cidadegeminada>
               <cidadegeminada>Sarajevo</cidadegeminada>
               <cidadegeminada>Rio de Janeiro</cidadegeminada>
               <cidadegeminada>Santiago</cidadegeminada>
               <cidadegeminada>Pequim</cidadegeminada>
               <cidadegeminada>Bogotá</cidadegeminada>
               <cidadegeminada>San José</cidadegeminada>
               <cidadegeminada>Havana</cidadegeminada>
               <cidadegeminada>Santo Domingo</cidadegeminada>
               <cidadegeminada>Quito</cidadegeminada>
               <cidadegeminada>Cairo</cidadegeminada>
               <cidadegeminada>San Salvador</cidadegeminada>
               <cidadegeminada>Cannes</cidadegeminada>
               <cidadegeminada>Bordéus</cidadegeminada>
               <cidadegeminada>Paris</cidadegeminada>
               <cidadegeminada>Berlim</cidadegeminada>
               <cidadegeminada>Berlim</cidadegeminada>
               <cidadegeminada>Guatemala</cidadegeminada>
               <cidadegeminada>Tegucigalpa</cidadegeminada>
               <cidadegeminada>Roma</cidadegeminada>
               <cidadegeminada>Trípoli</cidadegeminada>
               <cidadegeminada>Nouakchott</cidadegeminada>
               <cidadegeminada>Mexico</cidadegeminada>
               <cidadegeminada>Mexico</cidadegeminada>
               <cidadegeminada>Rabat</cidadegeminada>
               <cidadegeminada>Manágua</cidadegeminada>
               <cidadegeminada>Panama</cidadegeminada>
               <cidadegeminada>Assunção</cidadegeminada>
               <cidadegeminada>Lima</cidadegeminada>
               <cidadegeminada>Huacho</cidadegeminada>
               <cidadegeminada>Warszawa</cidadegeminada>
               <cidadegeminada>Lisboa</cidadegeminada>
               <cidadegeminada>Drobeta-Turnu Severin</cidadegeminada>
               <cidadegeminada>Moscovo</cidadegeminada>
               <cidadegeminada>Móstoles</cidadegeminada>
               <cidadegeminada>Abu Dhabi</cidadegeminada>
               <cidadegeminada>San Juan</cidadegeminada>
               <cidadegeminada>Miami</cidadegeminada>
               <cidadegeminada>Nova Iorque</cidadegeminada>
               <cidadegeminada>Montevidéu</cidadegeminada>
               <cidadegeminada>Caracas</cidadegeminada>
               <cidadegeminada>Libertador</cidadegeminada>
               <cidadegeminada>Belgrado</cidadegeminada>
               <cidadegeminada>Malabo</cidadegeminada>
          </cidadesgeminadas>
          <latitude>40.4167</latitude>
          <longitude>-3.70325</longitude>
          <altitude>659</altitude>
          <nhabitantes>3266126</nhabitantes>
          <codigopostal>28005</codigopostal>
     </cidade>
     <cidade>
          <nome>Yenne</nome>
          <pais>Senegal</pais>
          <bandeirapais>https://dwpt1kkww6vki.cloudfront.net/img/drapeau/120/184.png</bandeirapais>
          <capital>false</capital>
          <clima>Clima semiárido (Classificação climática de Köppen-Geiger: BSh)</clima>
          <fuso>UTC +0:00 (Africa/Dakar)</fuso>
          <linguagens>
               <lingua>Francesa</lingua>
          </linguagens>
          <monumentos>
               <monumento>//upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Yenne_depuis_Vierge.jpg/275px-Yenne_depuis_Vierge.jpg</monumento>
          </monumentos>
          <cidadesgeminadas />
          <latitude>14.651</latitude>
          <longitude>-17.1839</longitude>
          <altitude>6</altitude>
          <nhabitantes>37202</nhabitantes>
     </cidade>
     <cidade>
          <nome>Lisboa</nome>
          <pais>Portugal</pais>
          <bandeirapais>https://dwpt1kkww6vki.cloudfront.net/img/drapeau/120/170.png</bandeirapais>
          <bandeiracidade>https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Bandeira_municipal_de_Lisboa.png/90px-Bandeira_municipal_de_Lisboa.png</bandeiracidade>
          <capital>true</capital>
          <presidente>Fernando Medina</presidente>
          <clima>Clima mediterrânico (Classificação climática de Köppen-Geiger: Csa)</clima>
          <fuso>UTC +0:00 (Europe/Lisbon)</fuso>
          <website>https://www.lisboa.pt</website>
          <area uni="km2">84.8</area>
          <densidade uni="hab_km2">5981.4</densidade>
          <linguagens>
               <lingua>Português</lingua>
               <lingua>Mirandese</lingua>
          </linguagens>
          <monumentos>
               <monumento>//upload.wikimedia.org/wikipedia/commons/thumb/4/41/Lisbon_%2836831596786%29_%28cropped%29.jpg/280px-Lisbon_%2836831596786%29_%28cropped%29.jpg</monumento>
               <monumento>//upload.wikimedia.org/wikipedia/commons/thumb/3/31/Rua_Augusta_Arch_-_April_2019_%28cropped%29.jpg/139px-Rua_Augusta_Arch_-_April_2019_%28cropped%29.jpg</monumento>
               <monumento>//upload.wikimedia.org/wikipedia/commons/thumb/6/65/Lisboa_IMG_6805_%2820499138133%29.jpg/139px-Lisboa_IMG_6805_%2820499138133%29.jpg</monumento>
               <monumento>//upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Belem_Tower_-_April_2019_%282%29.jpg/139px-Belem_Tower_-_April_2019_%282%29.jpg</monumento>
               <monumento>//upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Se_Cathedral_%2834242766515%29_%28cropped%29.jpg/139px-Se_Cathedral_%2834242766515%29_%28cropped%29.jpg</monumento>
               <monumento>//upload.wikimedia.org/wikipedia/commons/thumb/5/59/Parque_das_Na%C3%A7%C3%B5es_Lisboa_%28cropped%29.jpg/280px-Parque_das_Na%C3%A7%C3%B5es_Lisboa_%28cropped%29.jpg</monumento>
          </monumentos>
          <cidadesgeminadas>
               <cidadegeminada>Rio de Janeiro</cidadegeminada>
               <cidadegeminada>Salvador</cidadegeminada>
               <cidadegeminada>São Paulo</cidadegeminada>
               <cidadegeminada>São Paulo</cidadegeminada>
               <cidadegeminada>Brasília</cidadegeminada>
               <cidadegeminada>Salvador</cidadegeminada>
               <cidadegeminada>Praia</cidadegeminada>
               <cidadegeminada>Macao</cidadegeminada>
               <cidadegeminada>Pereira</cidadegeminada>
               <cidadegeminada>Manizales</cidadegeminada>
               <cidadegeminada>Zagreb</cidadegeminada>
               <cidadegeminada>Cacheu</cidadegeminada>
               <cidadegeminada>Bissau</cidadegeminada>
               <cidadegeminada>Budapeste</cidadegeminada>
               <cidadegeminada>Budapeste</cidadegeminada>
               <cidadegeminada>Malaca</cidadegeminada>
               <cidadegeminada>Rabat</cidadegeminada>
               <cidadegeminada>Maputo</cidadegeminada>
               <cidadegeminada>Guimarães</cidadegeminada>
               <cidadegeminada>São Tomé</cidadegeminada>
               <cidadegeminada>Madrid</cidadegeminada>
               <cidadegeminada>Tunes</cidadegeminada>
               <cidadegeminada>Jersey City</cidadegeminada>
               <cidadegeminada>Caracas</cidadegeminada>
               <cidadegeminada>Libertador</cidadegeminada>
          </cidadesgeminadas>
          <latitude>38.7071</latitude>
          <longitude>-9.13549</longitude>
          <altitude>4</altitude>
          <nhabitantes>507220</nhabitantes>
          <codigopostal>1100</codigopostal>
     </cidade>
     <cidade>
          <nome>Sevilha</nome>
          <pais>Espanha</pais>
          <bandeirapais>https://dwpt1kkww6vki.cloudfront.net/img/drapeau/120/194.png</bandeirapais>
          <bandeiracidade>https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Sevilla%2C_Spain.svg/100px-Flag_of_Sevilla%2C_Spain.svg.png</bandeiracidade>
          <capital>false</capital>
